#spring:
#  datasource:
#    codog:
#      jdbc-url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
#      username: root
#      password: Codogroot
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      minimum-idle: 10
#      maximum-pool-size: 20
